# -*- coding: utf-8 -*-
"""U2A1. PROBLEMARIO. Operaciones matriciales y vectoriales

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15BmUxozlxvEOuJxciCfT7BG73_ovqgGi

# U2A1. PROBLEMARIO. Operaciones matriciales y vectoriales
## El presente repositorio reúne una colección de ejercicios de álgebra lineal implementados en  New Notebook mediante la librería NumPy, con el propósito de fortalecer la comprensión y aplicación práctica de conceptos fundamentales de esta disciplina matemática. A través de ejemplos interactivos ejecutados en entornos como Jupyter Notebook, se busca no solo analizar la teoría, sino que también observar su comportamiento al llevarla al plano computacional. Cada actividad incluye operaciones con matrices y vectores, permitiendo visualizar sus resultados, patrones y propiedades, lo cual facilita el aprendizaje y vincula el álgebra lineal con áreas como la ingeniería, la robótica, la computación científica y el procesamiento de datos.

## Objetivos Generales
* Reforzar los conocimientos teóricos de álgebra lineal mediante su implementación en Python.
* Facilitar la comprensión de las operaciones matriciales y vectoriales a través de ejemplos prácticos y visuales.
* Promover el uso de herramientas computacionales modernas como NumPy y Jupyter Notebook para la resolución de problemas matemáticos.

### Elaboro: Carmen Hernandez Fraire.
"""



"""#Ejercicio 1: Suma de matrices

Dadas dos matrices A y B:

A = [[2, 4, 6], [1, 3, 5], [7, 9, 11]]
B = [[12, 10, 8], [6, 4, 2], [0, -2, -4]]

Realiza la suma de estas dos matrices y encuentra la matriz resultante C = A + B.
"""

import numpy as np

# EJERCICIO 1: Suma de matrices
print("\nEJERCICIO 1: Suma de matrices")
A1 = np.array([[2, 4, 6], [1, 3, 5], [7, 9, 11]])
B1 = np.array([[12, 10, 8], [6, 4, 2], [0, -2, -4]])
print("Matriz A:\n", A1)
print("Matriz B:\n", B1)
print("Operación: C = A + B")
print("Resultado:\n", A1 + B1)

"""Ejercicio 2: Multiplicación de matrices

Dadas dos matrices A y B:

A = [[2, 1], [3, 4], [5, 6]]
B = [[7, 8], [9, 10]]

Realiza la multiplicación de estas dos matrices y encuentra la matriz resultante C = A * B.
"""

# EJERCICIO 2: Multiplicación de matrices
print("\n EJERCICIO 2: Multiplicación de matrices ")
A2 = np.array([[2, 1], [3, 4], [5, 6]])
B2 = np.array([[7, 8], [9, 10]])
print("Matriz A:\n", A2)
print("Matriz B:\n", B2)
print("Operación: C = A * B")
print("Resultado:\n", A2 @ B2)

"""Ejercicio 3: Inversión de matriz

Dada la matriz cuadrada A:

A = [[4, 7, 2], [2, 6, 8], [3, 1, 9]]

Encuentra la matriz inversa de A, denotada como A^(-1).
"""

# EJERCICIO 3: Inversa de matriz
print("\n EJERCICIO 3: Inversa de matriz ")
A3 = np.array([[4, 7, 2], [2, 6, 8], [3, 1, 9]])
print("Matriz A:\n", A3)
print("Operación: A^(-1)")
print("Resultado:\n", np.linalg.inv(A3))

"""Ejercicio 4: Resolución de sistema de ecuaciones lineales

Dado el sistema de ecuaciones lineales:

2x + y + z = 8
3x + 5y + 2z = 21
x + 2y + 4z = 11

Escribe este sistema en forma matricial AX = B, donde X es el vector de incógnitas [x, y, z] y B es el vector de términos constantes. Luego, resuelve el sistema para encontrar X
"""

# EJERCICIO 4: Sistema AX = B

print("\n EJERCICIO 4: Resolución de sistema AX = B")
A4 = np.array([[2, 1, 1],
               [3, 5, 2],
               [1, 2, 4]])
B4 = np.array([8, 21, 11])
print("Matriz A:\n", A4)
print("Vector B:\n", B4)
print("Operación: Resolver AX = B")
print("Resultado X:\n", np.linalg.solve(A4, B4))

"""Ejercicio 5: Cálculo de determinante

Dada la matriz cuadrada A:

A = [[3, -2, 1], [0, 5, 4], [2, 1, 7]]

Calcula el determinante de A.
"""

#  EJERCICIO 5: Determinante
print("\n EJERCICIO 5: Determinante de una matriz ")
A5 = np.array([[3, -2, 1], [0, 5, 4], [2, 1, 7]])
print("Matriz A:\n", A5)
print("Operación: det(A)")
print("Resultado:", np.linalg.det(A5))

"""Ejercicio 6: Producto cruz de vectores

Dados dos vectores A y B en el espacio tridimensional:

A = [2, 3, -1]
B = [1, -2, 4]

Calcula el producto cruz entre A y B, denotado como A x B.
"""

#  EJERCICIO 6: Producto Cruz
print("\nEJERCICIO 6: Producto cruz A x B ")
A6 = np.array([2, 3, -1])
B6 = np.array([1, -2, 4])
print("Vector A:", A6)
print("Vector B:", B6)
print("Operación: A x B")
print("Resultado:", np.cross(A6, B6))

"""Ejercicio 7: Proyección ortogonal

Dado un vector V = [5, -3, 2] y un vector U = [2, 1, 2], encuentra la proyección ortogonal de V sobre U.
"""

#  EJERCICIO 7: Proyección ortogonal
print("\n== EJERCICIO 7: Proyección de V sobre U ")
V7 = np.array([5, -3, 2])
U7 = np.array([2, 1, 2])
print("Vector V:", V7)
print("Vector U:", U7)
print("Operación: Proyección de V sobre U")
proy = (np.dot(V7, U7) / np.dot(U7, U7)) * U7
print("Resultado:", proy)

"""Ejercicio 8: Producto escalar de proyecciones

Supongamos que tienes tres vectores V = [3, -1, 2], U = [2, 2, -1], y W = [1, 4, -2]. Encuentra el producto escalar de la proyección de V sobre U con la proyección de V sobre W.
"""

# EJERCICIO 8: Producto escalar de proyecciones
import numpy as np
V = np.array([3, -1, 2], dtype=float)
U = np.array([2, 2, -1], dtype=float)
W = np.array([1, 4, -2], dtype=float)

def proj(v, u):
    denom = np.dot(u, u)
    if np.isclose(denom, 0):
        raise ValueError("Vector u es cero.")
    return (np.dot(v, u) / denom) * u

proj_V_on_U = proj(V, U)
proj_V_on_W = proj(V, W)

dot_product = np.dot(proj_V_on_U, proj_V_on_W)

print("Proyección de V sobre U:", proj_V_on_U)
print("Proyección de V sobre W:", proj_V_on_W)
print("\nProducto escalar entre ambas proyecciones:", dot_product)

"""Ejercicio 9: Ortogonalización de Gram-Schmidt

Dado un conjunto de vectores linealmente independientes:

v1 = [1, 1, 0]
v2 = [1, 2, 1]
v3 = [2, 1, 3]

Aplica el proceso de ortogonalización de Gram-Schmidt para obtener un conjunto ortogonal equivalente a los vectores originales.
"""

# EJERCICIO 9: Gram-Schmidt
print("\nEJERCICIO 9: Ortogonalización Gram-Schmidt ")
v1 = np.array([1, 1, 0])
v2 = np.array([1, 2, 1])
v3 = np.array([2, 1, 3])
print("Vectores iniciales:")
print("v1 =", v1)
print("v2 =", v2)
print("v3 =", v3)
print("Operación: Gram-Schmidt")

u1 = v1
u2 = v2 - (np.dot(v2, u1)/np.dot(u1, u1))*u1
u3 = v3 - (np.dot(v3, u1)/np.dot(u1, u1))*u1 - (np.dot(v3, u2)/np.dot(u2, u2))*u2

print("Resultado:")
print("u1 =", u1)
print("u2 =", u2)
print("u3 =", u3)

"""Ejercicio 10: Espacio nulo

Dada una matriz A en forma escalonada reducida por filas:

A = [[1, 2, 0, 3], [0, 1, 0, 2], [0, 0, 1, 1]]

Encuentra una base para el espacio nulo de A, es decir, los vectores que satisfacen Av = 0, donde v es un vector columna.
"""

# EJERCICIO 10: Espacio nulo
print("\n EJERCICIO 10: Espacio nulo de A ")
A10 = np.array([[1, 2, 0, 3],
                [0, 1, 0, 2],
                [0, 0, 1, 1]])
print("Matriz A:\n", A10)
print("Operación: Encontrar v tal que A·v = 0")

# Variable libre x4 = t
t = 1
x4 = t
x3 = -x4
x2 = -2*x4
x1 = -(2*x2 + 3*x4)

vector_nulo = np.array([x1, x2, x3, x4])
print("Resultado (base del espacio nulo):", vector_nulo)